[package]
name = "hangman-rs"
version = "0.1.0"
authors = ["iTzBoboCz <iTzBoboCz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
termion = "1.5.5"
stringsort = "2.0.0"